### ISSUE TITLE
I can't import this library

### ISSUE THREAD

**Issue by willowTank** [newraina/react-actionsheet#2]
`import Actionsheet from 'react-actionsheet/src';`
![image](https://user-images.githubusercontent.com/24641385/45993742-812f8980-c090-11e8-82da-4ddb38398396.png)

**Comment by zhaofeng-shu33** [comment]
Indeed.

**Comment by newraina** [comment]
fixed in v1.2.0

`import Actionsheet from 'react-actionsheet`

usage example: https://codesandbox.io/s/kx3vpvxo57?fontsize=14
